# Generated by Django 3.2 on 2023-06-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20230615_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
    ]
