# Generated by Django 3.2 on 2023-06-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_alter_review_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title_id',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('title', 'author')},
        ),
    ]
