# Generated by Django 3.2 on 2023-06-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('title', 'author')},
        ),
    ]
