# Generated by Django 3.2 on 2023-06-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_auto_20230618_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
